### ISSUE TITLE
PiecewiseAffine被提示速度太慢，没有问题吗？

### ISSUE THREAD

**Issue by zoucap** [Heron0625/PBT#2]
UserWarning: This augmenter is very slow. Try to use ``ElasticTransformation`` instead, which is at least 10x faster.
使用ElasticTransformation来替换PiecewiseAffine会产生什么不良影响吗？

**Comment by Heron0625** [comment]
我们在训练的时候并没有开启额外的数据增强。我推测应该效果差不多。

**Comment by zoucap** [comment]
请问作者有考虑过重构代码吗？

**Comment by Heron0625** [comment]
目前来说并无重构的必要。config.yml中有参数控制是否开启增强。

**Comment by YangBo0411** [comment]
> 目前来说并无重构的必要。config.yml中有参数控制是否开启增强。

请问下应该如何关闭数据增强，我在config.yml设置aug:为false和none都会报速度太慢的错误：
UserWarning: This augmenter is very slow. Try to use ElasticTransformation instead, which is at least 10x faster.
